log:
  level: DEBUG
  dir: logs
  rotation_enabled: true
  rotation: "10 MB"
  retention: "7 days"
  compression: zip

  format_console: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{extra[filename]}</cyan>:<cyan>{extra[line_no]}</cyan> - <level>{message}</level>"
  format_file: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {extra[filename]}:{extra[line_no]} - {message}"
